name: BuildPages

on: [push]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r .build/requirements.txt
      - name: Run Build
        run: python3 .build/main.py
      - name: Commit If it has Changes
        run: |
          git add -N ./docs
            if ! git diff --exit-code --quiet
            then
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git add ./docs
              git commit -m "Build Update"
              git push
            fi